routes/index.py
import os
import uuid
from config import admin_mail
from flask import (
    render_template,
    request,
    redirect,
    session,
    url_for,
    Blueprint,
    abort,
    send_from_directory,
    current_app)
from werkzeug.datastructures import FileStorage

from models.reply import Reply
from models.topic import Topic
from models.user import User
# from routes import current_user, cache
from routes import current_user

import json

from utils import log
from models.message import send_mail

main = Blueprint('index', __name__)

"""
用户在这里可以
    访问首页
    注册
    登录

用户登录后, 会写入 session, 并且定向到 /profile
"""

# import gevent
import time


def format_time(unix_timestamp):
    # enum Year():
    #     2013
    #     13
    # f = Year.2013
    f = '%Y-%m-%d %H:%M:%S'
    value = time.localtime(unix_timestamp)
    formatted = time.strftime(f, value)
    return formatted


@main.route("/")
def index():
    # t = threading.Thread()
    # t.start()
    # gevent.spawn()
    time.sleep(0.5)
    # print('time type', time.sleep, gevent.sleep)
    u = current_user()
    return render_template("login.html", user=u)


# @main.route("/register", methods=['POST'])
# def register():
#     form = request.form.to_dict()
#     # 用类函数来判断
#     u = User.register(form)
#     return redirect(url_for('.index'))


@main.route("/login", methods=['POST'])
def login():
    form = request.form
    u = User.validate_login(form)
    if u is None:
        return redirect(url_for('.index'))
    else:
        # session 中写入 user_id
        # session_id = str(uuid.uuid4())
        # key = 'session_id_{}'.format(session_id)
        # log('index login key <{}> user_id <{}>'.format(key, u.id))
        # cache.set(key, u.id)

        # redirect_to_index = redirect(url_for('topic.index'))
        # response = current_app.make_response(redirect_to_index)
        # response.set_cookie('session_id', value=session_id)
        # 转到 topic.index 页面
        # return response
        session['user_id'] = u.id
        return redirect(url_for('topic.index'))


@main.route("/register/view")
def register_index():

    return render_template('new.html')


@main.route("/register/send", methods=['POST'])
def register():
    form = request.form.to_dict()
    # 用类函数来判断
    u = User.register(form)
    return redirect(url_for('.index'))


def created_topic(user_id):
    # O(n)
    ts = Topic.all(user_id=user_id)
    return ts
    #
    # k = 'created_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     ts = Topic.all(user_id=user_id)
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #     return ts


def replied_topic(user_id):
    # O(k)+O(m*n)
    rs = Reply.all(user_id=user_id)
    ts = []
    for r in rs:
        t = Topic.one(id=r.topic_id)
        ts.append(t)
    return ts
    #
    #     sql = """
    # select * from topic
    # join reply on reply.topic_id=topic.id
    # where reply.user_id=1
    # """
    # k = 'replied_topic_{}'.format(user_id)
    # if cache.exists(k):
    #     v = cache.get(k)
    #     ts = json.loads(v)
    #     return ts
    # else:
    #     # ts = Topic.select()
    #     #   .join(Reply, 'id', 'topic_id')
    #     #   .where(user_id=user_id)
    #     #   .all()
    #     rs = Reply.all(user_id=user_id)
    #     ts = []
    #     for r in rs:
    #         t = Topic.one(id=r.topic_id)
    #         ts.append(t)
    #
    #     v = json.dumps([t.json() for t in ts])
    #     cache.set(k, v)
    #
    #     return ts


@main.route('/profile')
def profile():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'profile.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/user/<int:id>')
def user_detail(id):
    u = User.one(id=id)
    if u is None:
        abort(404)
    else:
        return render_template('profile.html', user=u)


@main.route('/image/add', methods=['POST'])
def avatar_add():
    file: FileStorage = request.files['avatar']
    # file = request.files['avatar']
    # filename = file.filename
    # ../../root/.ssh/authorized_keys
    # images/../../root/.ssh/authorized_keys
    # filename = secure_filename(file.filename)
    suffix = file.filename.split('.')[-1]
    if suffix not in ['gif', 'jpg', 'jpeg']:
        abort(400)
        log('不接受的后缀, {}'.format(suffix))
    else:
        filename = '{}.{}'.format(str(uuid.uuid4()), suffix)
        path = os.path.join('images', filename)
        file.save(path)

        u = current_user()
        User.update(u.id, image='/images/{}'.format(filename))

        return redirect(url_for('.profile'))


@main.route('/images/<filename>')
def image(filename):
    # 不要直接拼接路由，不安全，比如
    # http://localhost:3000/images/..%5Capp.py
    # path = os.path.join('images', filename)
    # print('images path', path)
    # return open(path, 'rb').read()
    # if filename in os.listdir('images'):
    #     return
    return send_from_directory('images', filename)


@main.route('/setting')
def set():
    print('running profile route')
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        created = created_topic(u.id)
        replied = replied_topic(u.id)
        return render_template(
            'setting.html',
            user=u,
            created=created,
            replied=replied
        )


@main.route('/setting/update', methods=['POST'])
def set_update():
    form = request.form.to_dict()
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        u = current_user()
        User.update(u.id, signature=form['signature'])
        User.update(u.id, username=form['username'])

        return redirect(url_for('.profile'))


@main.route('/setting/updatepass', methods=['POST'])
def set_updatepass():
    form = request.form.to_dict()
    u = current_user()
    if u is None:
        return redirect(url_for('.index'))
    else:
        u = current_user()
        d = dict(
            username=u.username,
            password=form['old_pass'],
        )
        if User.validate_login(d):
            User.update(u.id, password=User.salted_password(form['new_pass']))
        return redirect(url_for('.profile'))


@main.route('/forgot')
def forgot():
    return render_template('forgot.html')

a={}


@main.route("/reset/send", methods=["POST"])
def reset_send():
    form = request.form.to_dict()
    username = form['username']
    u = User.one(username=username)
    token = str(uuid.uuid4())
    a[u.id] = token
    subject = '点击链接'
    author = admin_mail
    to = u.email
    content = 'http://49.235.32.57/reset/view?token={}'.format(token)
    send_mail(subject, author, to, content)
    return redirect(url_for('.index'))


@main.route("/reset/view")
def reset_view():
    if 'token' not in request.args:
        return redirect(url_for('.index'))
    else:
        return render_template('reset_view.html', token=request.args['token'])


@main.route('/reset/update/<token>', methods=["POST"])
def reset_update(token):
    form = request.form.to_dict()
    for key in a:
        if a[key] == token:
            u = User.one(id=int(key))
            u.update(u.id, password=User.salted_password(form['password']))
    return redirect(url_for('.index'))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.reply import Reply
from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    u = current_user()
    if board_id == -1:
        ms = Topic.all()
        b = sorted(ms, key=lambda m: m.created_time, reverse=True)
    else:
        ms = Topic.all(board_id=board_id)
        b = sorted(ms, key=lambda m: m.created_time, reverse=True)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", user=u, ms=b, token=token, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    b = Board.one(id=m.board_id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, b=b)


@main.route("/delete")
@csrf_required
# @author_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


# @main.route('/user/<string:username>')
# def user(username):
#     u = User.one(username=username)
#     topics = Topic.all(user_id=u.id)
#
#     b = sorted(topics, key=lambda m: m.created_time, reverse=True)
#
#     replies = Reply.all(user_id=u.id)
#     replies_topics = []
#     for r in replies:
#         a = Topic.one(id=r.topic_id)
#         replies_topics.append(a)
#     replies_topics = sorted(replies_topics, key=lambda m: m.created_time, reverse=True)
#     return render_template('topic/user.html', u=u, topics=b, ms=replies_topics)

templates/for.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="/static/images/icons/favicon.ico"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/bootstrap/css/bootstrap.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/fonts/iconic/css/material-design-iconic-font.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animate/animate.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/css-hamburgers/hamburgers.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/animsition/css/animsition.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/select2/select2.min.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/vendor/daterangepicker/daterangepicker.css">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="/static/css/util.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
<div class="limiter">
		<div class="container-login100">
			<div class="wrap-login100">
				<form class="login100-form validate-form">
					<span class="login100-form-title p-b-26">
						Welcome
					</span>

    <form class="form-horizontal" method="post" action="/reset/send">
        <div class="control-group">
            <label class="control-label">用户名</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="username">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="忘记密码">
        </div>
    </form>


<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
	<script src="/static/vendor/jquery/jquery-3.2.1.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/animsition/js/animsition.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/bootstrap/js/popper.js"></script>
	<script src="/static/vendor/bootstrap/js/bootstrap.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/select2/select2.min.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/daterangepicker/moment.min.js"></script>
	<script src="/static/vendor/daterangepicker/daterangepicker.js"></script>
<!--===============================================================================================-->
	<script src="/static/vendor/countdowntime/countdowntime.js"></script>
<!--===============================================================================================-->
	<script src="/static/js/main.js"></script>

</body>
</html>

templates/forgot.html
<!DOCTYPE html>
<head>
	<title>忘记密码</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link href="/static/css-1/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/templatemo_style.css" rel="stylesheet" type="text/css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<div class="container">
		<div class="col-md-12">
			<h1 class="margin-bottom-15">重设密码</h1>
			<form class="form-horizontal templatemo-forgot-password-form templatemo-container" role="form" action="/reset/send" method="post">
				<div class="form-group">
		          <div class="col-md-12">
		          	请输入您的用户名，稍后会将重置密码邮件发送至您注册邮箱
		          </div>
		        </div>
                <form class="form-horizontal" method="post" action="/reset/send">
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="text" class="input-xlarge" name="username">
		          </div>              
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		            <input type="submit" value="确定" class="btn btn-danger">



		          </div>
		        </div>
		      </form>
		</div>
	</div>

</body>
</html>

templates/login.html
<!DOCTYPE html>
<head>
	<title>web论坛</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<link href="/static/css-1/font-awesome.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/templatemo_style.css" rel="stylesheet" type="text/css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<div class="container">
		<div class="col-md-12">
			<h1 class="margin-bottom-15">Welcome</h1>
			<form class="form-horizontal templatemo-container templatemo-login-form-1 margin-bottom-30" role="form" action="{{ url_for('index.login') }}" method="post">
		        <div class="form-group">
		          <div class="col-xs-12">		            
		            <div class="control-wrapper">
		            	<input type="text" class="form-control" id="username"
                               placeholder="username" name="username" value="test">
		            </div>
		          </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		          	<div class="control-wrapper">
		            	<input type="password" class="form-control" id="password"
                               placeholder="password" name="password" value="123">
		            </div>
		          </div>
		        </div>
		        <div class="form-group">
		          <div class="col-md-12">
		          	<div class="control-wrapper">
		          		<input type="submit" value="登录" class="btn btn-info">
		          		<a href="/forgot" class="text-right pull-right">忘记密码?</a>
		          	</div>
		          </div>
		        </div>

		      </form>
		      <div class="text-center">
		      	<a href="/register/view" class="templatemo-create-new">没有账户？现在注册</a>
		      </div>
		</div>
	</div>

</body>
</html>

templates/loginold.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" action={{ url_for(".login") }}>
    <input type="text" name="user_name" placeholder="user_name">
    <button type="submit">提交</button>
</form>
</body>
</html>

templates/new.html
<!DOCTYPE html>
<head>
	<title>创建用户</title>
	<meta name="keywords" content="" />
	<meta name="description" content="" />
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link href="/static/css-1/bootstrap.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/bootstrap-theme.min.css" rel="stylesheet" type="text/css">
	<link href="/static/css-1/templatemo_style.css" rel="stylesheet" type="text/css">
    <link href="/static/css/style.css" rel="stylesheet" type="text/css">
</head>
<body class="templatemo-bg-gray">
	<h1 class="margin-bottom-15">创建用户</h1>
	<div class="container">
		<div class="col-md-12">
			<form class="form-horizontal templatemo-create-account templatemo-container" role="form" action="/register/send" method="post">
				<div class="form-inner">


			        <div class="form-group">
			          <div class="col-md-12">
			            <label for="username" class="control-label">用户名</label>
			            <input type="text" class="form-control" id="username" placeholder="" name="username">
			          </div>

			        </div>
                    <div class="form-group">
			          <div class="col-md-12">
			            <label for="username" class="control-label">邮箱</label>
			            <input type="email" class="form-control" id="email" placeholder="" name="email">
			          </div>
			        </div>
			        <div class="form-group">
			          <div class="col-md-12">
			            <label for="password" class="control-label">密码</label>
			            <input type="password" class="form-control" id="password" placeholder="" name="password">
			          </div>
			        </div>

			        <div class="form-group">
			          <div class="col-md-12">
			            <input type="submit" value="注册" class="btn btn-info">
			            <a href="/" class="pull-right">登录</a>
			          </div>
			        </div>
				</div>
		      </form>
		</div>
	</div>
	<!-- Modal -->
	<div class="modal fade" id="templatemo_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
	        <h4 class="modal-title" id="myModalLabel">Terms of Service</h4>
	      </div>
	      <div class="modal-body">
	      	<p>This form is provided by <a rel="nofollow" href="http://www.cssmoban.com/page/1">Free HTML5 Templates</a> that can be used for your websites. Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Morbi leo risus, porta ac consectetur ac, vestibulum at eros.</p>
	        <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Aenean lacinia bibendum nulla sed consectetur. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Donec sed odio dui. Donec ullamcorper nulla non metus auctor fringilla. Cras mattis consectetur purus sit amet fermentum. Cras justo odio, dapibus ac facilisis in, egestas eget quam.</p>
	        <p>Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor.</p>
	      </div>
	      <div class="modal-footer">
	        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
	      </div>
	    </div>
	  </div>
	</div>
	<script type="text/javascript" src="js/jquery-1.11.1.min.js"></script>
	<script type="text/javascript" src="js/bootstrap.min.js"></script>

</body>
</html>

templates/profile.html
{% extends "topic/base.html" %}
{% block title %}个人资料{% endblock%}
{% block main %}
    <div id="main">
    <div>
        <div id="sidebar">
        <div class="panel">
            <div class="header">
                <span class="col_fade">个人信息</span>
            </div>
            <div class="inner">
                <div class="user_card">
                    <div>
                        <a class="user_avatar">
                            <img src="{{ user.image }}">
                        </a>
                        <span class="user_name"><a class="dark">{{ user.username }}</a></span>


                            <div class="space clearfix"></div>
                            <span class="signature">


                                    {{ user.signature}}


                            </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="panel">
            <div class="inner">
                <a href="/topic" id="create_topic_btn">
                    <span class="span-success">返回主页</span>
                </a>
            </div>
        </div>
    </div>
        <div id='content'>
            <div class='panel'>
                <div class='header'>
                    <ul class='breadcrumb'>
                        <li><a href='/topic'>主页</a><span class='divider'>/</span></li>
                    </ul>
                </div>
                <div class='inner userinfo'>
                    <div class='user_big_avatar'>
                        <img src="{{ user.image }}" class="user_big_avatar" title="{{ user.username }}">
                    </div>
                    <a class="dark">{{ user.username }}</a>

                    <p class="col_fade">{{ user.created_time | format_time }}</p>

                </div>
            </div>

            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>最近创建的话题</span>
                </div>

                {# 创建话题版面 #}
                {% for t in created %}
                <div class="cell">

                    <a class="user_avatar pull-left">
                        <img src="{{ user.image }}">
                    </a>

                    <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ t.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ t.views }}
                        </span>
                    </span>


                    <a class="last_time pull-right" >
                        <img class="user_small_avatar" src="{{ user.image }}">
                        <span class="last_active_time">{{ t.created_time | format_time }}</span>
                    </a>

                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                    {{ t.title }}
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>

            <div class='panel'>
                <div class='header'>
                    <span class='col_fade'>最近参与的话题</span>
                 </div>
                {# 参与话题版面 #}
                {% for r in replied %}
                <div class="cell">

                    <span class="reply_count pull-left">
                        <span class="count_of_replies" title="回复数">
                            {{ r.replies() | count }}
                        </span>
                        <span class="count_seperator">/</span>
                        <span class="count_of_visits" title="点击数">
                            {{ r.views }}
                        </span>
                    </span>


                    <a class="last_time pull-right">
                        <span class="last_active_time">{{ r.created_time | format_time }}</span>
                    </a>

                    <div class="topic_title_wrapper">

                        <a class="topic_title" href="{{ url_for('topic.detail', id=r.id) }}">
                            {{ r.title }}
                        </a>
                    </div>
                </div>
                {% endfor %}

            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/reset_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <title>更改密码</title>
</head>
<body>
<form class="form-horizontal" method="post" action="{{ url_for('.reset_update', token=token) }}">

        <div class="control-group">
            <label class="control-label">新密码</label>
            <div class="controls">
                <input type="text" class="input-xlarge" name="password">
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" class="span-primary" value="确定">
        </div>
    </form>
</body>
</html>

templates/setting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/css/set.min.css">
    <title>设置</title>
</head>
<body>
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
{#      <a class='brand' >#}
{##}
{#          <img src="//static2.cnodejs.org/public/images/cnodejs_light.svg" />#}
{##}
{#      </a>#}
{##}
{#      <form id='search_form' class='navbar-search' action="/search">#}
{#        <input type='text' id='q' name='q' class='search-query span3' value=''/>#}
{#      </form>#}
      <ul class='nav pull-right'>
        <li><a href='/topic'>首页</a></li>
        <li><a href='/profile'>个人</a></li>
        <li><a href='/message'>私信</a></li>
        <li><a href='/setting'>设置</a></li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
  </div>

<div id='main'>
  <div id='sidebar'>

  <div class='panel'>

    <div class='header'>
      <span class='col_fade'>个人信息</span>
    </div>
    <div class='inner'>
      <div class='user_card'>
  <div>
    <a class='user_avatar' href="/profile">
      <img src="{{ user.image }} " >
    </a>
    <span class='user_name'><a class='dark' >{{ user.username }}</a></span>


    <div class="space clearfix"></div>
    <span class="signature">
        {{ user.signature }}
    </span>
  </div>
</div>

 <div class="panel">
    <div class='inner'>
      <a href='/topic' id='create_topic_btn'>
        <span class='span-success'>返回主页</span>
      </a>
    </div>
  </div>
</div>
      </div>
       </div>
<div id='content'>
  <div class='panel'>
    <div class='header'>
       <span class='col_fade'>基础信息</span>
    </div>
    <div class='inner'>


      <form id='setting_form' class='form-horizontal' action='/setting/update' method="post">
        <div class='control-group'>
          <label class='control-label' for='username'>用户名</label>

          <div class='controls'>
            <input class='input-xlarge ' id='username' name='username' size='30' type='text' >
          </div>
        </div>

        <div class='control-group'>
          <label class='control-label' for='signature'>个性签名</label>

          <div class='controls'>
            <input class='input-xlarge' id='signature' name='signature' size='30'>
          </div>
        </div>

        <div class='form-actions'>
          <button type='submit' class='span-primary submit_btn' >
            保存设置</button>
        </div>
      </form>
    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>更改密码</span>
    </div>
    <div class='inner'>
      <form id='change_pass_form' class='form-horizontal' action='/setting/updatepass' method='post'>
        <div class='control-group'>
          <label class='control-label' for='old_pass'>当前密码</label>

          <div class='controls'>
            <input class='input-xlarge' type='password' id='old_pass' name='old_pass' size='30'/>
          </div>
        </div>
        <div class='control-group'>
          <label class='control-label' for='new_pass'>新密码</label>

          <div class='controls'>
            <input class='input-xlarge' type='password' id='new_pass' name='new_pass' size='30'/>
          </div>
        </div>

        <div class='form-actions'>
          <button type='submit' class='span-primary submit_btn'>
           更改密码</button>
        </div>
      </form>
    </div>
  </div>

 <div class='panel'>
    <div class='header'>
      <span class='col_fade'>设置头像</span>
    </div>
    <div class='inner' >
 <form method="post"
      action="{{ url_for('.avatar_add')}}"
      enctype="multipart/form-data"
>
    <input type="file" name="avatar" >
    <button type="submit" class='span-primary submit_btn'>上传头像</button>
</form>
</div>

</body>
</html>