models/topic.py
import time

from sqlalchemy import String, Integer, Column, Text, UnicodeText, Unicode

from models.base_model import SQLMixin, db
from models.user import User
from models.reply import Reply


class Topic(SQLMixin, db.Model):
    views = Column(Integer, nullable=False, default=0)
    title = Column(Unicode(50), nullable=False)
    content = Column(UnicodeText, nullable=False)
    user_id = Column(Integer, nullable=False)
    board_id = Column(Integer, nullable=False)

    @classmethod
    def new(cls, form, user_id):
        form['user_id'] = user_id
        m = super().new(form)
        return m
    #
    # @classmethod
    # def delete(cls, form, user_id):
    #     form['user_id'] = user_id
    #     m = super().new(form)
    #     return m

    @classmethod
    def get(cls, id):
        m = cls.one(id=id)
        m.views += 1
        m.save()
        return m

    def user(self):
        u = User.one(id=self.user_id)
        return u

    def replies(self):
        ms = Reply.all(topic_id=self.id)
        return ms

    def reply_count(self):
        count = len(self.replies())
        return count

models/user.py
import hashlib

from sqlalchemy import Column, String, Text

import config
import secret
from models.base_model import SQLMixin, db


class User(SQLMixin, db.Model):
    __tablename__ = 'User'
    """
    User 是一个保存用户数据的 model
    现在只有两个属性 username 和 password
    """
    username = Column(String(50), nullable=False)
    password = Column(String(100), nullable=False)
    image = Column(String(100), nullable=False, default='/images/3.jpg')
    email = Column(String(50), nullable=False, default=config.test_mail)
    signature = Column(String(200), nullable=False, default=' “这家伙很懒，什么个性签名都没有留下。”')

    @staticmethod
    def salted_password(password, salt='$!@><?>HUI&DWQa`'):
        salted = hashlib.sha256((password + salt).encode('ascii')).hexdigest()
        return salted

    @classmethod
    def register(cls, form):
        name = form.get('username', '')
        print('register', form)
        if len(name) > 2 and User.one(username=name) is None:
            # 错误，只应该 commit 一次
            # u = User.new(form)
            # u.password = u.salted_password(pwd)
            # User.session.add(u)
            # User.session.commit()
            form['password'] = User.salted_password(form['password'])
            u = User.new(form)
            return u
        else:
            return None

    @classmethod
    def update(cls, id, **kwargs):
        # u.username = 'test'
        # db.session.add(u)
        # db.session.commit()
        m = cls.query.filter_by(id=id).first()
        for name, value in kwargs.items():
            setattr(m, name, value)

        db.session.add(m)
        db.session.commit()

    @classmethod
    def validate_login(cls, form):
        query = dict(
            username=form['username'],
            password=User.salted_password(form['password']),
        )
        print('validate_login', form, query)
        return User.one(**query)

routes/reply.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
    Request)

from models.message import Messages
from routes import *

from models.reply import Reply


main = Blueprint('reply', __name__)


def users_from_content(content):
    # 内容 @123 内容
    # 如果用户名含有空格 就不行了 @name 123
    # 'a b c' -> ['a', 'b', 'c']
    parts = content.split()
    users = []

    for p in parts:
        if p.startswith('@'):
            username = p[1:]
            u = User.one(username=username)
            print('users_from_content <{}> <{}> <{}>'.format(username, p, parts))
            if u is not None:
                users.append(u)

    return users


def send_mails(sender, receivers, reply_link, reply_content):
    print('send_mail', sender, receivers, reply_content)
    content = '链接：{}\n内容：{}'.format(
        reply_link,
        reply_content
    )
    for r in receivers:
        title = '你被 {} AT 了'.format(sender.username)
        Messages.send(
            title=title,
            content=content,
            sender_id=sender.id,
            receiver_id=r.id
        )


@main.route("/add", methods=["POST"])
def add():
    form = request.form
    u = current_user()

    content = form['content']
    users = users_from_content(content)
    send_mails(u, users, request.referrer, content)

    form = form.to_dict()
    m = Reply.new(form, user_id=u.id)
    return redirect(url_for('topic.detail', id=m.topic_id))

routes/topic.py
from flask import (
    render_template,
    request,
    redirect,
    url_for,
    Blueprint,
)

from models.reply import Reply
from routes import *

from models.topic import Topic
from models.board import Board

main = Blueprint('topic', __name__)


@main.route("/")
def index():
    board_id = int(request.args.get('board_id', -1))
    u = current_user()
    if board_id == -1:
        ms = Topic.all()
        b = sorted(ms, key=lambda m: m.created_time, reverse=True)
    else:
        ms = Topic.all(board_id=board_id)
        b = sorted(ms, key=lambda m: m.created_time, reverse=True)
    token = new_csrf_token()
    bs = Board.all()
    return render_template("topic/index.html", user=u, ms=b, token=token, bs=bs, bid=board_id)


@main.route('/<int:id>')
def detail(id):
    m = Topic.get(id)
    b = Board.one(id=m.board_id)
    # 传递 topic 的所有 reply 到 页面中
    return render_template("topic/detail.html", topic=m, b=b)


@main.route("/delete")
@csrf_required
# @author_required
def delete():
    id = int(request.args.get('id'))
    u = current_user()
    print('删除 topic 用户是', u, id)
    Topic.delete(id)
    return redirect(url_for('.index'))


@main.route("/new")
def new():
    board_id = int(request.args.get('board_id'))
    bs = Board.all()
    # return render_template("topic/new.html", bs=bs, bid=board_id)
    token = new_csrf_token()
    return render_template("topic/new.html", bs=bs, token=token, bid=board_id)


@main.route("/add", methods=["POST"])
@csrf_required
def add():
    form = request.form.to_dict()
    u = current_user()
    Topic.new(form, user_id=u.id)
    return redirect(url_for('.index'))


# @main.route('/user/<string:username>')
# def user(username):
#     u = User.one(username=username)
#     topics = Topic.all(user_id=u.id)
#
#     b = sorted(topics, key=lambda m: m.created_time, reverse=True)
#
#     replies = Reply.all(user_id=u.id)
#     replies_topics = []
#     for r in replies:
#         a = Topic.one(id=r.topic_id)
#         replies_topics.append(a)
#     replies_topics = sorted(replies_topics, key=lambda m: m.created_time, reverse=True)
#     return render_template('topic/user.html', u=u, topics=b, ms=replies_topics)

templates/topic/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">

<head>
<body>

<!-- navbar -->
<div class='navbar'>
  <div class='navbar-inner'>
    <div class='container'>
      <ul class='nav pull-right'>
        <li><a href='/topic'>首页</a></li>
        <li><a href='/profile'>个人</a></li>
        <li><a href='/message'>私信</a></li>
        <li><a href='/setting'>设置</a></li>



        <li><a href='/register/view'>注册</a></li>
        <li><a href='/'>登录</a></li>

      </ul>
      <a class="btn btn-navbar" id="responsive-sidebar-trigger">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
    </div>
  </div>
</div>

{% block main %}
{% endblock %}
<div class="bottom" style="text-align:center">
    <a href="http://beian.miit.gov.cn" target="_blank" >沪ICP备19027455号</a>
</div>

</body>

templates/topic/detail.html
{% extends "topic/base.html" %}
{% block title %}{{ topic.title }}{% endblock%}
{% block main %}
<div id="main">
    <div id="content">
        <div class='panel'>
            <div class='header topic_header'>
        <span class="topic_full_title">
			{{ topic.title }}
      	</span>
                <div class="changes">
            <span>
                发布于 {{ topic.created_time | format_time }}
            </span>
                    <span>
                {% set u = topic.user() %}
                作者
                         <a>{{ u.username }}</a>
        	</span>
                    <span>
          	    {{ topic.views }} 次浏览
        	</span>
                    <span>
                来自 问答
            </span>
                </div>
            </div>

            <div class='inner topic'>
                <div class='topic_content'>
                    <div class="markdown-text">{{ topic.content }}</div>
                </div>
            </div>
        </div>
    </div>

    <div class='panel'>
        <div class='header'>
            <span class='col_fade'>
                <!-- 过滤器 -->
                {{ topic.replies() | count }} 回复
            </span>
        </div>
        {% for r in topic.replies() %}
            {% set u = r.user() %}
            <div class='cell reply_area reply_item'>
                <div class='author_content'>
                    <div class='user_info'>
                        <a class='dark reply_author'>
                            {{ u.username }}
                        </a>
                        <a class="reply_time">
                            {{ loop.index }}楼 / {{ loop.length }}楼 •
                            <span>{{ r.created_time | format_time }}</span>
                        </a>
                    </div>
                    <div class='user_action'>
                    <span>
                        <i class="fa up_btn
                          fa-thumbs-o-up
                          invisible" title="喜欢"></i>
                        <span class="up-count">
                        </span>
                    </span>
                    </div>
                </div>
                <div class='reply_content from-leiwei1991'>
                    <div class="markdown-text">{{ r.content }}</div>

                </div>
            </div>
        {% endfor %}
        <div>
            <form action="{{ url_for('reply.add') }}" method="post">
                <input type="hidden" name="topic_id" value="{{ topic.id }}">
                <textarea name="content"></textarea>
                <button>添加回复</button>
            </form>
        </div>
    </div>
</div>


<link rel="stylesheet" href="/static/css/bootstrap.min.css">
<link rel="stylesheet" href="/static/css/style.css">
<script src="https://cdn.bootcss.com/marked/0.3.19/marked.min.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/prism.js"></script>
<script src="https://cdn.bootcss.com/prism/1.13.0/plugins/autoloader/prism-autoloader.min.js"></script>
<script>
    var e = function (sel) {
        return document.querySelector(sel)
    }

    var es = function (sel) {
        return document.querySelectorAll(sel)
    }

    var markContents = function () {
        // markdown -> html 的处理放在高亮前面
        // 因为高亮是针对 html 格式的
        // lang -> language 不需要转 prism 自动转了
        var contentDivs = es('.markdown-text')
        for (var i = 0; i < contentDivs.length; i++) {
            var contentDiv = contentDivs[i]
            console.log('pre marked', contentDiv.textContent)
            var content = marked(contentDiv.textContent)
            console.log('after marked', content)
            contentDiv.innerHTML = content
        }
    }

    var highlight = function() {
         // 自动加载对应的语言 不然要手动加入各个语言的 js
        Prism.plugins.autoloader.languages_path = 'https://cdn.bootcss.com/prism/1.13.0/components/'
    }

    var __main = function () {
        markContents()
        highlight()
    }

    __main()

</script>

{% endblock %}

templates/topic/index.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
    <!--<meta charset="UTF-8">-->
    <!--<title>bbs club</title>-->
    <!--<link rel="stylesheet" href="/static/css/bootstrap.min.css">-->
    <!--<link rel="stylesheet" href="/static/css/style.css">-->
<!--</head>-->
<!--<body>-->
{% extends "topic/base.html" %}
{% block title %}论坛主页{% endblock%}
{% block main %}

<div id="main">
    <div id="sidebar">
         <div class='panel'>

    <div class='header'>
      <span class='col_fade'>个人信息</span>
    </div>
    <div class='inner'>
      <div class='user_card'>
  <div>
    <a class='user_avatar' href="/profile">
      <img src="{{ user.image }} " >
    </a>
    <span class='user_name'><a class='dark' >{{ user.username }}</a></span>


    <div class="space clearfix"></div>
    <span class="signature">
        {{ user.signature }}
    </span>
  </div>
</div>
</div>


        <div class="panel">
            <div class="inner">
                <a href="/topic/new?board_id={{ bid }}" class="create_topic_btn">
                    <span class="span-success">发布话题</span>
                </a>
            </div>
        </div>
    </div>
         </div>
    <div id="content">
        <div class="panel">
            <div class="header">
                <a href="/topic"
                   class="topic-tab current-tab">
                    全部的帖子
                </a>

                {% for b in bs %}
                <a href="/topic?board_id={{ b.id }}"
                   class="topic-tab current-tab">
                    {{ b.title }}
                </a>
                {% endfor %}
            </div>
            <div class="inner post">
                <div class="topic_list">
                    {% for t in ms %}
                    <div class="cell">
                        <div class="topic_title_wrapper">
                            <a class="topic_title" href="{{ url_for('topic.detail', id=t.id) }}">
                                {{ t.title }}
                            </a>
                            <span>{{ t.replies() | count }} / {{ t.views }}</span>
                            <!--<a class="topic_title" href="{{ url_for('topic.delete', id=t.id) }}">-->
                            <a class="topic_title" href="{{ url_for('topic.delete', id=t.id, token=token) }}">
                                删除
                            </a>
                            <a class="last_time pull-right">
                            <span class="last_active_time">{{ t.created_time | format_time }}</span>
                            </a>

                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();

</script>

{% endblock %}


<!--</body>-->
<!--</html>-->

templates/topic/new.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
<form id="create_topic_form" method="post" action="{{ url_for('.add', token=token) }}">
<!--<form id="create_topic_form" method="post" action="{{ url_for('.add') }}">-->
    <fieldset>
        <textarea autofocus class='span9' id='title'
                  name='title' rows='1'
                  placeholder="标题字数 10 字以上"></textarea>
        <span class="tab-selector">选择版块：</span>
        <select name="board_id" id="board" required>
            {% for b in bs %}
                {% if bid == b.id %}
                    <option value="{{ b.id }}" selected >{{ b.title }}</option>
                {% else %}
                    <option value="{{ b.id }}" >{{ b.title }}</option>
                {% endif %}
            {% endfor %}
        </select>
        <div class='markdown_editor in_editor'>
          <div class='markdown_in_editor'>
            <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
            <div class='editor_buttons'>
              <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
            </div>
          </div>
        </div>
    </fieldset>
</form>
                </div>
            </div>
        </div>
    </div>
<script>
  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>bbs club</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link rel="stylesheet" href="/static/lib/editor/editor.css">
    <link rel="stylesheet" href="/static/lib/webuploader/webuploader.css">
    <script src="/static/lib/jquery-3.0.0.min.js"></script>
    <script src="/static/lib/markdownit.js"></script>
    <script src="/static/lib/webuploader/webuploader.withoutimage.js"></script>
    <script src="/static/lib/editor/editor.js"></script>
    <script src="/static/lib/editor/ext.js"></script>
</head>
<body>
    <div id="main">
        <div id="content">
            <div class="panel">
                <div class="inner post">
                    <form id="create_topic_form" method="post" action="{{ url_for('.add') }}">
                        <fieldset>
                            <textarea autofocus class='span9' id='title' name='title' rows='1' placeholder="标题字数 10 字以上"></textarea>
                            <div class='markdown_editor in_editor'>
                              <div class='markdown_in_editor'>
                                <textarea class='editor' name='content' rows='20' placeholder='文章支持 Markdown 语法, 请注意标记代码'></textarea>
                                <div class='editor_buttons'>
                                  <input type="submit" class='span-primary submit_btn' data-loading-text="提交中" value="提交">
                                </div>
                              </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
<script>

  (function () {
    var editor = new Editor();
    editor.render($('.editor')[0]);
  })();
</script>
</body>
</html>

templates/topic/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>个人主页</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
    <link rel="stylesheet" href="/static/css/style.css">
    <link href="https://cdn.bootcss.com/github-markdown-css/3.0.1/github-markdown.min.css" rel="stylesheet">
</head>
<body>
<div id='content'>
  <div class='panel'>
    <div class='header'>
      <ul class='breadcrumb'>
        <li><a href='/'>主页</a><span class='divider'>/</span></li>
      </ul>
    </div>
    <div class='inner userinfo'>
      <div class='user_big_avatar'>
        <img src="{{ u.image }}" class="user_avatar" />
      </div>
      <a class='dark'>{{ u.username }}</a>


      <p class='col_fade'>
          <span>
                注册于 {{ u.created_time  }}
          </span>
      </p>

    </div>
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>最近创建的话题</span>
    </div>
     {% for t in topics %}
                <div class="cell">
                    <a class="user_avatar pull-left" href="{{ url_for('gua_topic.user', username=u.username) }}">
                        <img src="/static/doge.gif" >
                    </a>
                    <span class="reply_count pull-left">
                       {{ t.replies() | count }} / {{ t.views }}

                    </span>

                    <a class="last_time pull-right" href="{{ url_for('gua_topic.user', username=u.username) }}">
                        <img class="user_small_avatar" src="/static/doge.gif">
                        <span class="last_active_time">{{ t.created_time  }}</span>
                    </a>

                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('gua_topic.detail', id=t.id) }}">
                            {{ t.title }}
                        </a>

                    </div>
                </div>

        {% endfor %}
  </div>

  <div class='panel'>
    <div class='header'>
      <span class='col_fade'>最近参与的话题</span>
    </div>

     {% for t in ms %}
                <div class="cell">
                    <a class="user_avatar pull-left" href="{{ url_for('gua_topic.user', username=u.username) }}">

                        <img src="/static/doge.gif">
                    </a>
                    <span class="reply_count pull-left">
                         {{ t.replies() | count }} / {{ t.views }}
                    </span>

                    <a class="last_time pull-right" href="{{ url_for('gua_topic.user', username=u.username) }}">
                        <img class="user_small_avatar" src="/static/doge.gif">
                        <span class="last_active_time">{{ t.created_time  }}</span>
                    </a>

                    <div class="topic_title_wrapper">
                        <a class="topic_title" href="{{ url_for('gua_topic.detail', id=t.id) }}">
                            {{ t.title }}
                        </a>

                    </div>
                </div>
    {% endfor %}
  </div>
</div>

</body>
</html>